update grok schema to match new logging structure
xtuml/erebus pull request #66
Opened 2024-06-12 10:20 UTC by AdrianMontaguSmartDCSIT

2024-06-12 10:23 UTC, AdrianMontaguSmartDCSIT commented
GitHub Actions end to end tests that test the test harness' functionality with the protocol verifier are required to be written. These will:
- pull prod version of protocol verifier from munin
- run and verify a performance test
- run and verify a functional test

2024-06-19 09:18 UTC, FreddieMatherSmartDCSIT approved these changes
Really good stuff here!

2024-06-19 09:20 UTC, FreddieMatherSmartDCSIT requested changes

2024-06-19 09:20 UTC, FreddieMatherSmartDCSIT commented on end_to_end_test_files/docker-compose.prod.yml
> +    image: ghcr.io/xtuml/protocol_verifier:latest
Can we have this as a tagged version please

2024-06-19 18:25 UTC, FreddieMatherSmartDCSIT approved these changes

2024-06-20 07:19 UTC, merged